### ISSUE TITLE
Failure in test suites is not documented?

### ISSUE THREAD

**Issue by goldbergyoni** [michaelleeallen/jest-junit-reporter#8] opened 2017-09-24 10:01 UTC
Hi,

I ran few test suites, most failed to run due to compilation error (test didnt actually ran). One suite ran successfully with 2 tests that passed.

The output .xml file reports 2 tests where both succeeded. Doesn't it make sense to report all the failing tests in the tests suites as failures (Even though they didn't run, they failed to compile)?

Yoni

**Comment by StanleyGoldman** [comment] 2018-03-04 18:30
I'm seeing the same issue as @i0natan. I'm not sure what the right fix is yet.

**Comment by StanleyGoldman** [comment] 2018-03-04 19:06
So I compared this to `jest-html-reporter` and I found that it has the same behavior.

I realized over time that I had a `... || true` added to my test script to prevent the test script from failing if a testsuite failed to run, I realized that is my mistake. A testsuite failing to run is a critical error and my test script should fail as a result. The error message in that failure will tell me what testsuite failed.

**Comment by michaelleeallen** [comment] 2018-04-28 01:05
Im not sure it is the responsibility of the test report formatter to alert you that your tests failed to run. This seems like it would be the responsibility of jest itself. In fact, jest provides a mechanism to ensure your test cases run as intended with `expect.hasAssertions()` (see https://facebook.github.io/jest/docs/en/expect.html#expecthasassertions). Also, there is `expect.assertions(Number)`(see https://facebook.github.io/jest/docs/en/expect.html#expectassertionsnumber)

**Comment by StanleyGoldman** [comment] 2018-05-01 15:23
Yea.. I dont think this is a bug

**Comment by michaelleeallen** [comment] 2018-07-13 13:05
Closing this issue as it is not a bug with this module. See comment above for explanation.

**Closed as completed by michaelleeallen** 2018-07-13 13:05 UTC
